services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090/tcp"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      vpn_net:
        ipv4_address: 10.0.0.90 # IP fixe ajoutée pour Prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000/tcp"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      vpn_net:
        ipv4_address: 10.0.0.30 # IP fixe ajoutée pour Grafana
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    networks:
      vpn_net:
        ipv4_address: 10.0.0.91
    restart: unless-stopped

  fail2ban-exporter:
    image: registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:latest
    container_name: fail2ban-exporter
    volumes:
      - /var/run/fail2ban/fail2ban.sock:/var/run/fail2ban/fail2ban.sock:ro
    networks:
      vpn_net:
        ipv4_address: 10.0.0.92
    restart: unless-stopped

volumes:
  grafana-storage:

networks:
  vpn_net:
    external: true
    name: vpn_net