services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard-gateway
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SERVERURL=${SERVERURL}
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=10.0.0.53
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    networks:
      vpn_net:
        ipv4_address: 10.0.0.2
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    container_name: pihole-dns
    environment:
      - TZ=${TZ}
      - WEBPASSWORD=${WEBPASSWORD}
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "8080:80/tcp"
    networks:
      vpn_net:
        ipv4_address: 10.0.0.53
    restart: unless-stopped

networks:
  vpn_net:
    external: true
