# Chiffrer avec : ansible-vault encrypt Service/ansible-setup/group_vars/all/secrets.yml
vault_pihole_password: "TonMotDePassePiholeSecurise"
vault_grafana_password: "TonMotDePasseGrafanaSecurise"
vault_wireguard_server_url: "X.X.X.X" # Votre IP Publique ou nom de domaine
